version: "3.8"
services: 
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_rails_app_development
    ports:
      - "5432:5432"

  rails-api:
    build:
      context: ./rails-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails-api:/var/www/rails-api:cached
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_rails_app_development
    user: "1000:1000"

  nextjs:
    build:
      context: ./nextjs
      target: dev
    command: yarn dev
    environment:
      - NODE_ENV=development 
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - rails-api

volumes:
  postgres_data:
